apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: OPENSHIFT_CONTAINER-imagestream
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "OPENSHIFT_CONTAINER-buildconfig"
spec:
  source:
    type: Dockerfile
    dockerfile: >-
      FROM eclipse-temurin:21

      ENV LANGUAGE='en_US:en'
      
      WORKDIR /app

      USER 1001

      COPY --chown=1001 . ./devops

      RUN sh devops/docker-curl-version.sh

      CMD ["sh", "devops/docker-entrypoint.sh"]
  strategy:
    dockerStrategy: {}  
  output:
    to:
      kind: ImageStreamTag
      name: OPENSHIFT_CONTAINER-imagestream:VERSION
