apiVersion: "v1"
kind: "Pod"
spec:
  serviceAccountName: jenkins
  containers:
    - name: oc
      image: registry.redhat.io/openshift4/ose-cli
      command:
        - cat
      tty: true
    - name: "jnlp"
      image: "jenkins/inbound-agent:4.11-1-jdk11"
      volumeMounts:
        - mountPath: /etc/pki/ca-trust/source/anchors
          name: jenkins-trusted-ca-bundle
      env:
        - name: "GIT_SSL_CAINFO"
          value: /etc/pki/ca-trust/source/anchors/ca-bundle.crt
        - name: "HOME"
          value: /home/jenkins/agent
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"    
  volumes:
    - configMap:
        defaultMode: 420
        name: jenkins-trusted-ca-bundle
        optional: true
      name: jenkins-trusted-ca-bundle