
package oracle.reports.rwclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RWWebService", targetNamespace = "http://oracle.reports/rwclient/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RWWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerInfo", targetNamespace = "http://oracle.reports/rwclient/", className = "oracle.reports.rwclient.GetServerInfo")
    @ResponseWrapper(localName = "getServerInfoResponse", targetNamespace = "http://oracle.reports/rwclient/", className = "oracle.reports.rwclient.GetServerInfoResponse")
    public String getServerInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobInfo", targetNamespace = "http://oracle.reports/rwclient/", className = "oracle.reports.rwclient.GetJobInfo")
    @ResponseWrapper(localName = "getJobInfoResponse", targetNamespace = "http://oracle.reports/rwclient/", className = "oracle.reports.rwclient.GetJobInfoResponse")
    public String getJobInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAPIVersion", targetNamespace = "http://oracle.reports/rwclient/", className = "oracle.reports.rwclient.GetAPIVersion")
    @ResponseWrapper(localName = "getAPIVersionResponse", targetNamespace = "http://oracle.reports/rwclient/", className = "oracle.reports.rwclient.GetAPIVersionResponse")
    public String getAPIVersion();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "killJob", targetNamespace = "http://oracle.reports/rwclient/", className = "oracle.reports.rwclient.KillJob")
    @ResponseWrapper(localName = "killJobResponse", targetNamespace = "http://oracle.reports/rwclient/", className = "oracle.reports.rwclient.KillJobResponse")
    public String killJob(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runJob", targetNamespace = "http://oracle.reports/rwclient/", className = "oracle.reports.rwclient.RunJob")
    @ResponseWrapper(localName = "runJobResponse", targetNamespace = "http://oracle.reports/rwclient/", className = "oracle.reports.rwclient.RunJobResponse")
    public String runJob(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

}
