
package apimailws.apimailwsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApiMailWS", targetNamespace = "http://bse.com.uy/services/apimailWS/apimailWS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApiMailWS {


    /**
     * 
     * @param enviarMailRequest
     * @return
     *     returns apimailws.apimailwsclient.EnviarMailResponse
     * @throws GenericFault_Exception
     * @throws ValidationsFault
     */
    @WebMethod(operationName = "EnviarMail", action = "EnviarMail")
    @WebResult(name = "EnviarMailResponse", targetNamespace = "http://bse.com.uy/services/apimailWS/apimailWS", partName = "EnviarMailResponse")
    public EnviarMailResponse enviarMail(
        @WebParam(name = "EnviarMailRequest", targetNamespace = "http://bse.com.uy/services/apimailWS/apimailWS", partName = "EnviarMailRequest")
        EnviarMailRequest enviarMailRequest)
        throws GenericFault_Exception, ValidationsFault
    ;

}
