
package oracle.reports.rwclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RWWebService", targetNamespace = "http://oracle.reports/rwclient/", wsdlLocation = "http://desa-app:8888/reports/rwwebservice?wsdl")
public class RWWebService_Service
    extends Service
{

    private final static URL RWWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException RWWEBSERVICE_EXCEPTION;
    private final static QName RWWEBSERVICE_QNAME = new QName("http://oracle.reports/rwclient/", "RWWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://desa-app:8888/reports/rwwebservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RWWEBSERVICE_WSDL_LOCATION = url;
        RWWEBSERVICE_EXCEPTION = e;
    }

    public RWWebService_Service() {
        super(__getWsdlLocation(), RWWEBSERVICE_QNAME);
    }

    public RWWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RWWEBSERVICE_QNAME, features);
    }

    public RWWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, RWWEBSERVICE_QNAME);
    }

    public RWWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RWWEBSERVICE_QNAME, features);
    }

    public RWWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RWWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RWWebService
     */
    @WebEndpoint(name = "RWWebServicePort")
    public RWWebService getRWWebServicePort() {
        return super.getPort(new QName("http://oracle.reports/rwclient/", "RWWebServicePort"), RWWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RWWebService
     */
    @WebEndpoint(name = "RWWebServicePort")
    public RWWebService getRWWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://oracle.reports/rwclient/", "RWWebServicePort"), RWWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RWWEBSERVICE_EXCEPTION!= null) {
            throw RWWEBSERVICE_EXCEPTION;
        }
        return RWWEBSERVICE_WSDL_LOCATION;
    }

}
