
package apimailws.apimailwsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApiMailWSService", targetNamespace = "http://bse.com.uy/services/apimailWS/apimailWS", wsdlLocation = "http://jboss-test.bse.com.uy:9080/apimailWS/v2/apimailWS?wsdl")
public class ApiMailWSService
    extends Service
{

    private final static URL APIMAILWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException APIMAILWSSERVICE_EXCEPTION;
    private final static QName APIMAILWSSERVICE_QNAME = new QName("http://bse.com.uy/services/apimailWS/apimailWS", "ApiMailWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://jboss-test.bse.com.uy:9080/apimailWS/v2/apimailWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APIMAILWSSERVICE_WSDL_LOCATION = url;
        APIMAILWSSERVICE_EXCEPTION = e;
    }

    public ApiMailWSService() {
        super(__getWsdlLocation(), APIMAILWSSERVICE_QNAME);
    }

    public ApiMailWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APIMAILWSSERVICE_QNAME, features);
    }

    public ApiMailWSService(URL wsdlLocation) {
        super(wsdlLocation, APIMAILWSSERVICE_QNAME);
    }

    public ApiMailWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APIMAILWSSERVICE_QNAME, features);
    }

    public ApiMailWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApiMailWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApiMailWS
     */
    @WebEndpoint(name = "ApiMailWSPort")
    public ApiMailWS getApiMailWSPort() {
        return super.getPort(new QName("http://bse.com.uy/services/apimailWS/apimailWS", "ApiMailWSPort"), ApiMailWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApiMailWS
     */
    @WebEndpoint(name = "ApiMailWSPort")
    public ApiMailWS getApiMailWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bse.com.uy/services/apimailWS/apimailWS", "ApiMailWSPort"), ApiMailWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APIMAILWSSERVICE_EXCEPTION!= null) {
            throw APIMAILWSSERVICE_EXCEPTION;
        }
        return APIMAILWSSERVICE_WSDL_LOCATION;
    }

}
